/*
 * Project: banker
 * File: codes.go (5/9/23, 4:45 PM)
 *
 * Copyright (C) Megakit Systems 2017-2023, Inc - All Rights Reserved
 * @link https://www.megakit.pro
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Anton (antonstremovskyy) Stremovskyy <stremovskyy@gmail.com>
 */

package fondy_status

import "fmt"

/*
StatusCode Response codes
1000 General decline The cause of the error is unknown, detailed analysis is needed, contact the support service
1002 Application error The cause of the error is unknown, the detailed analysis is needed, contact the support service
1003 Invalid CVV2 code Incorrect CVV2 code. In some cases, you can get this error if the validity period of card was incorrect issuing bank
1004 Do not honor The card is blocked, the status was set, or it’s closed for online payments issuing bank
1005 Invalid format Invalid data format. Probable cause is too small payment amount issuing bank
1006 Merchant is not configured correctly Merchant settings on the side of are not correct
1007 Parameter `{param_name}` is incorrect One or more of the received parameters have an incorrect format, size or an invalid value merchant
1009 Parameter `{param_name}` is empty One or more of the received parameters are empty merchant
1010 Request Is empty Submitted request is empty merchant
1011 Parameter `{param_name}` is missing One or more required parameters are not sent merchant
1012 Currency `{currency}` is not available for this merchant `1396424` The merchant uses a currency that is not allowed or not configured on the side merchant
1013 Duplicate order `{order_id}` for merchant `1396424` The passed parameter order_id is not unique for this merchant merchant
1014 Invalid signature The signature generated by the merchant in the request is not correct merchant
1015 Invalid card number Incorrect card number issuing bank
1016 Merchant `1396424` not found Merchant is not registered
1017 No available payment systems Merchant is not allowed to use any of the payment methods that were sent in the request
1018 Order `{order_id}` not found Error is returned when requesting order status or reverse if no order is found
1019 Order `{order_id}` already has been completed Was made an attempt to pay the expired order merchant
1021 Unsupported Content-Type `{content_type}` When requesting a server, a non-HTTP header of Content-Type merchant
1023 Invalid amount Incorrect amount merchant
1024 3DSecure authentication failed 3DSecure password verification error issuing bank
1025 Invalid card expiry date Invalid card validity period issuing bank
1026 Only redirect method allowed The protocol used by the merchant is not allowed merchant
1027 Preauth not allowed Preauthorization is not available
1028 Custom design not found Custom design not found merchant
1034 Please do not use symbol `{separator}` in parameters The separator character can not be used in request parameters merchant
1035 Token not found An attempt to charge the client card by it’s token is unsuccessful. The token may have expired, or an invalid value has been used merchant
1036 Invoice is paid Invoice is paid merchant
1037 Decline, not sufficient funds Decline, not sufficient funds merchant
1040 Transaction amount exceeds card internet limit Transaction amount exceeds card internet limit merchant
1041 Card is in black list Card is in black list
1042 Stolen card Stolen card merchant
1043 Restricted Card Restricted Card merchant
1044 Lost card Lost card merchant
1045 Card is blocked by acquirer bank Card is blocked by acquirer bank
1046 Request contains non utf-8 symbol Request contains non utf-8 symbol merchant
1047 Card exceeds withdrawal frequency limit Card exceeds withdrawal frequency limit merchant
1048 Card exceeds withdrawal amount limit Card exceeds withdrawal amount limit merchant
1049 Unknown payment system error Unknown payment system error
1051 Declined by antifraud Declined by antifraud
1052 Order has expired Order has expired merchant
1053 3DSecure card verification failed. Directory server or issuer not available. 3DSecure card verification failed. Directory server or issuer not available. merchant
1054 Session expired Session expired merchant
1055 P2P limit exceeded P2P limit exceeded
1057 Sender card declined by issuer Sender card declined by issuer (is blocked) merchant
1058 Receiver card declined by issuer Receiver card declined by issuer (is blocked) merchant
1059 Transaction with rectoken not allowed for merchant Transaction with rectoken not allowed for merchant
1060 Recurring transaction not allowed for merchant Recurring transaction not allowed for merchant
1061 PIN tries exceeded PIN tries exceeded merchant
1062 Not permitted to merchant Transaction is not permitted to merchant
1063 Not permitted to client Transaction is not permitted to client merchant
1064 Call your bank Call your bank merchant
1065 Invalid transaction The transaction was rejected by the issuer bank merchant
1066 System malfunction System failure of acquirer bank
1067 Incorrect PIN Incorrect PIN merchant
1068 Format error Data format error merchant
1069 Reverse not allowed. Turnover is not enough. Reverse not allowed. Turnover is not enough.
1070 Transaction is routed to another terminal Transaction is routed to another terminal
1072 Recurring chain declined Recurring chain declined merchant
1073 3DSecure is mandatory for Maestro cards 3DSecure is mandatory for Maestro cards merchant
1074 P2P credit allowed only by rectoken P2P credit allowed only by rectoken
1078 Token deactivated by bank Token deactivated by bank
1075 3DSecure is mandatory 3DSecure is mandatory merchant
1079 Card is blocked by issuing bank Card is blocked by issuing bank merchant
1076 An error occurred while processing your payment.Invalid IBAN.Check the IBAN you entered, or use another IBAN An error occurred while processing your payment.Invalid IBAN.Check the IBAN you entered, or use another IBAN merchant
1080 Decline, exceeds receiving card count limit Decline, exceeds receiving card count limit merchant
1077 Merchant is not activated yet.Only test IBAN allowed Merchant is not activated yet.Only test IBAN allowed
1081 Insufficient funds on balance (p2p credit) Insufficient funds on balance (p2p credit)
1082 Token has expired Token has expired merchant
1083 Decline, exceeds receiving card amount limit Decline, exceeds receiving card amount limit merchant
1087 Terminal closed by acquiring bank Terminal blocked by acquiring bank
1086 Transaction already finished Transaction already finished merchant
1084 Only full refund allowed Only full refund allowed
1088 Lookup code attempts limit exceeded Lookup code attempts limit exceeded
1089 Acquiring bank request timeout Acquiring bank request timeout merchant
1090 P2P card credit not allowed for this country P2P card credit not allowed for this country
1091 Card not enrolled. Lookup required Lookup for p2p transfer is required
1092 Invalid phone number Phone number, provided by the customer is not valid
1096 Invalid E-mail Email, provided by the customer is not valid
1097 Decline, refer to card issuer Issuing bank declined transaction issuing bank
1098 SEPA: The customer’s payment is accepted, but then canceled before collection.merchant
1099 P2P credit is not available for this IP address Merchant need to provide servers IP list to support
1100 Operation not allowed Thistype of APIoperation is not allowed to merchant.Please contact support
1102 Antifraud decline.Prepaid cards are blocked Prepaid cards are limited prior agreement with the merchant merchant
1103 Receipt created Payment by receipt method.A receipt has been generated for the customer and payment is expected through the bank account.merchant
1104 Country not allowed by bank-acquirer The acquiring bank has limited certain countries
1105 Antifraud decline.Only full 3D-Secure allowed.Only payments with full 3D-Secure authentication are allowed
1106 Split error.Split payments not allowed for merchant.Splitting API not activated for this merchant merchant
1107 Split error.Settlement merchants have another company. An attempt to split the payment with an incorrect recipient merchant
1108 Split error.Merchants in purchase and reverse do not match.An error occurred while trying to make a reverse on a split payment.The merchant_id specified in the reverse does not match the merchant_id that was involved in the splitting of the original purchase merchant
1109 Order already captured with different amount Attempt to re-capture on a partialy-completed purchase merchant
1111 Your card is not supported.Please use card of {extended} The card of this payment system is not supported
1114 Settlement not allowed until order is captured Before splitting the pre-authorization payment, it must be completed (perform the capture operation) merchant
1115 Pick up card (no fraud) The issuing bank requests the card pick up, but the claim is not fraudulent
1116 Pick up card, special condition (fraud account) The issuing bank requests the card pick up, the claim is related to the fact of fraud or compromise
1117 Security violation Operations with this card are limited by the issuing bank
1120 Splitting amount does not correspond to purchase or capture amount An attempt to split a payment into an amount that differs from the original payment, or a capture operation
1122 Connection closed unexpectedly Technical error while connecting the acquiring bank
1123 Acquiring bank request timeout.Transaction reversed.Timeout of connection with the acquiring bank.The technical reverse of the operation has been performed
1125 Maestro cards are not allowed Maestro cards are limited to accept
*/
type StatusCode int

const (
	GeneralDecline                                            StatusCode = 1000
	ApplicationError                                          StatusCode = 1002
	InvalidCVV2Code                                           StatusCode = 1003
	DoNotHonor                                                StatusCode = 1004
	InvalidFormat                                             StatusCode = 1005
	MerchantIsNotConfiguredCorrectly                          StatusCode = 1006
	IncorrectParameter                                        StatusCode = 1007
	EmptyParameter                                            StatusCode = 1009
	RequestIsEmpty                                            StatusCode = 1010
	MissingParameter                                          StatusCode = 1011
	UnsupportedCurrency                                       StatusCode = 1012
	DuplicateOrder                                            StatusCode = 1013
	InvalidSignature                                          StatusCode = 1014
	InvalidCardNumber                                         StatusCode = 1015
	MerchantNotFound                                          StatusCode = 1016
	NoAvailablePaymentSystems                                 StatusCode = 1017
	OrderNotFound                                             StatusCode = 1018
	OrderAlreadyCompleted                                     StatusCode = 1019
	UnsupportedContentType                                    StatusCode = 1021
	InvalidAmount                                             StatusCode = 1023
	ThreeDSecureAuthenticationFailed                          StatusCode = 1024
	InvalidCardExpiryDate                                     StatusCode = 1025
	OnlyRedirectMethodAllowed                                 StatusCode = 1026
	PreauthNotAllowed                                         StatusCode = 1027
	CustomDesignNotFound                                      StatusCode = 1028
	DoNotUseSymbolInParameters                                StatusCode = 1034
	TokenNotFound                                             StatusCode = 1035
	InvoiceIsPaid                                             StatusCode = 1036
	DeclineNotSufficientFunds                                 StatusCode = 1037
	TransactionAmountExceedsCardInternetLimit                 StatusCode = 1040
	CardIsInBlackList                                         StatusCode = 1041
	StolenCard                                                StatusCode = 1042
	RestrictedCard                                            StatusCode = 1043
	LostCard                                                  StatusCode = 1044
	CardIsBlockedByAcquirerBank                               StatusCode = 1045
	RequestContainsNonUtf8Symbol                              StatusCode = 1046
	CardExceedsWithdrawalFrequencyLimit                       StatusCode = 1047
	CardExceedsWithdrawalAmountLimit                          StatusCode = 1048
	UnknownPaymentSystemError                                 StatusCode = 1049
	DeclinedByAntifraud                                       StatusCode = 1051
	OrderHasExpired                                           StatusCode = 1052
	ThreeDSecureCardVerificationFailed                        StatusCode = 1053
	SessionExpired                                            StatusCode = 1054
	P2PLimitExceeded                                          StatusCode = 1055
	SenderCardDeclinedByIssuer                                StatusCode = 1057
	ReceiverCardDeclinedByIssuer                              StatusCode = 1058
	TransactionWithRecTokenNotAllowedForMerchant              StatusCode = 1059
	RecurringTransactionNotAllowedForMerchant                 StatusCode = 1060
	PINTriesExceeded                                          StatusCode = 1061
	NotPermittedToMerchant                                    StatusCode = 1062
	NotPermittedToClient                                      StatusCode = 1063
	CallYourBank                                              StatusCode = 1064
	InvalidTransaction                                        StatusCode = 1065
	SystemMalfunction                                         StatusCode = 1066
	IncorrectPIN                                              StatusCode = 1067
	FormatError                                               StatusCode = 1068
	ReverseNotAllowed                                         StatusCode = 1069
	TransactionRoutedToAnotherTerminal                        StatusCode = 1070
	RecurringChainDeclined                                    StatusCode = 1072
	ThreeDSecureIsMandatoryForMaestroCards                    StatusCode = 1073
	P2PCreditAllowedOnlyByRecToken                            StatusCode = 1074
	ThreeDSecureIsMandatory                                   StatusCode = 1075
	CardIsBlockedByIssuingBank                                StatusCode = 1079
	PaymentProcessingError                                    StatusCode = 1076
	ExceedsReceivingCardCountLimit                            StatusCode = 1080
	MerchantNotActivatedYet                                   StatusCode = 1077
	InsufficientFundsOnBalance                                StatusCode = 1081
	TokenExpired                                              StatusCode = 1082
	ExceedsReceivingCardAmountLimit                           StatusCode = 1083
	TerminalBlockedByAcquiringBank                            StatusCode = 1087
	TransactionAlreadyFinished                                StatusCode = 1086
	OnlyFullRefundAllowed                                     StatusCode = 1084
	LookupCodeAttemptsLimitExceeded                           StatusCode = 1088
	AcquiringBankRequestTimeout                               StatusCode = 1089
	P2PCardCreditNotAllowedForThisCountry                     StatusCode = 1090
	CardNotEnrolledLookupRequired                             StatusCode = 1091
	InvalidPhoneNumber                                        StatusCode = 1092
	InvalidEmail                                              StatusCode = 1096
	CardIssuerDeclinedTransaction                             StatusCode = 1097
	CustomerPaymentAcceptedButThenCanceledBeforeCollection    StatusCode = 1098
	P2PCreditNotAvailableForThisIPAddress                     StatusCode = 1099
	OperationNotAllowed                                       StatusCode = 1100
	PrepaidCardsAreBlocked                                    StatusCode = 1102
	ReceiptCreated                                            StatusCode = 1103
	CountryNotAllowedByBankAcquirer                           StatusCode = 1104
	OnlyFull3DSecureAllowed                                   StatusCode = 1105
	SplitPaymentsNotAllowedForMerchant                        StatusCode = 1106
	SettlementMerchantsHaveAnotherCompany                     StatusCode = 1107
	MerchantsInPurchaseAndReverseDoNotMatch                   StatusCode = 1108
	OrderAlreadyCapturedWithDifferentAmount                   StatusCode = 1109
	CardNotSupportedPleaseUseCardOfExtended                   StatusCode = 1111
	SettlementNotAllowedUntilOrderIsCaptured                  StatusCode = 1114
	PickUpCardNoFraud                                         StatusCode = 1115
	PickUpCardSpecialConditionFraudAccount                    StatusCode = 1116
	SecurityViolation                                         StatusCode = 1117
	SplittingAmountDoesNotCorrespondToPurchaseOrCaptureAmount StatusCode = 1120
	ConnectionClosedUnexpectedly                              StatusCode = 1122
	AcquiringBankRequestTimeoutTransactionReversed            StatusCode = 1123
	MaestroCardsAreNotAllowed                                 StatusCode = 1125
)

func (s StatusCode) String() string {
	switch s {
	case GeneralDecline:
		return "General decline The cause of the error is unknown, detailed analysis is needed, contact the support service"
	case ApplicationError:
		return "Application error The cause of the error is unknown, detailed analysis is needed, contact the support service"
	case InvalidCVV2Code:
		return "Invalid CVV2 code Incorrect CVV2 code. In some cases, you can get this error if the validity period of card was incorrect issuing bank"
	case DoNotHonor:
		return "Do not honor The card is blocked, the status was set, or it’s closed for online payments issuing bank"
	case InvalidFormat:
		return "Invalid format Invalid data format. Probable cause is too small payment amount issuing bank"
	case MerchantIsNotConfiguredCorrectly:
		return "Merchant is not configured correctly Merchant settings on the side of are not correct"
	case IncorrectParameter:
		return "Parameter `{param_name}` is incorrect One or more of the received parameters have an incorrect format, size or an invalid value merchant"
	case EmptyParameter:
		return "Parameter `{param_name}` is empty One or more of the received parameters are empty merchant"
	case RequestIsEmpty:
		return "Request Is empty Submitted request is empty merchant"
	case MissingParameter:
		return "Parameter `{param_name}` is missing One or more required parameters are not sent merchant"
	case UnsupportedCurrency:
		return "Currency `{currency}` is not available for this merchant `1396424` The merchant uses a currency that is not allowed or not configured on the side merchant"
	case DuplicateOrder:
		return "Duplicate order `{order_id}` for merchant `1396424` The passed parameter order_id is not unique for this merchant merchant"
	case DeclinedByAntifraud:
		return "Declined by antifraud The transaction was declined by the antifraud system antifraud"
	case CardExceedsWithdrawalFrequencyLimit:
		return "Card exceeds withdrawal frequency limit The card has exceeded the limit on the number of transactions per day issuing bank"
	case CardExceedsWithdrawalAmountLimit:
		return "Card exceeds withdrawal amount limit The card has exceeded the limit on the amount of transactions per day issuing bank"
	case AcquiringBankRequestTimeout:
		return "Acquiring bank request timeout The acquiring bank did not respond in time acquiring bank"
	case RestrictedCard:
		return "Restricted card The card is blocked, the status was set, or it’s closed for online payments issuing bank"
	case CardIsBlockedByAcquirerBank:
		return "Card is blocked by acquirer bank The card is blocked, the status was set, or it’s closed for online payments issuing bank"
	case ReceiverCardDeclinedByIssuer:
		return "Receiver card declined by issuer Receiver card declined by issuer (is blocked) merchant"
	case PINTriesExceeded:
		return "PIN tries exceeded PIN tries exceeded merchant"
	}

	return fmt.Sprintf("Fondy StatusCode(%d)", s)
}
